add_subdirs("ext/EASTL")
add_subdirs("ext/abseil-cpp/absl")
add_subdirs("ext/spdlog")
add_subdirs("core")
add_subdirs("vstl")
add_subdirs("meta")
add_subdirs("ast")
add_subdirs("runtime")
add_subdirs("compile")
add_subdirs("dsl")
-- add_subdirs("py")
-- add_subdirs("remote")
add_subdirs("backends/dx")
add_subdirs("tests")
